services:
  localstack:
    image: localstack/localstack:3.1.0
    container_name: event-processor-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - event-processor-network

  event-processor:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.processor
    container_name: event-processor-service
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/event-queue
      - SQS_DLQ_URL=http://localstack:4566/000000000000/event-dlq
      - DYNAMODB_TABLE_NAME=events
      - SERVICE_PORT=8080
      - SCHEMA_PATH=/app/schemas/event-schema.json
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - event-processor-network

  event-producer:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.producer
    container_name: event-producer-service
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/event-queue
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - event-processor-network

networks:
  event-processor-network:
    driver: bridge