#!/bin/bash

# Simple test script for the event-processor system
# This script verifies that the basic infrastructure is working

set -e

echo "🧪 Testing Event Processor System"
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    local status=$1
    local message=$2
    if [ "$status" = "OK" ]; then
        echo -e "${GREEN}✅ $message${NC}"
    elif [ "$status" = "WARN" ]; then
        echo -e "${YELLOW}⚠️  $message${NC}"
    else
        echo -e "${RED}❌ $message${NC}"
    fi
}

# Check if services are running
echo -e "\n📋 Checking service status..."

if docker-compose ps | grep -q "Up"; then
    print_status "OK" "Docker services are running"
else
    print_status "ERROR" "Docker services are not running"
    echo "Please run: docker-compose up -d"
    exit 1
fi

# Check LocalStack health
echo -e "\n🏥 Checking LocalStack health..."
if curl -s http://localhost:4566/_localstack/health > /dev/null; then
    print_status "OK" "LocalStack is healthy"
else
    print_status "ERROR" "LocalStack is not responding"
    exit 1
fi

# Check Event Processor health
echo -e "\n🏥 Checking Event Processor health..."
if curl -s http://localhost:8080/health | grep -q "OK"; then
    print_status "OK" "Event Processor is healthy"
else
    print_status "ERROR" "Event Processor is not responding"
    exit 1
fi

# Check if DynamoDB tables exist
echo -e "\n🗄️  Checking DynamoDB tables..."
if docker exec event-processor-localstack awslocal dynamodb list-tables | grep -q "events"; then
    print_status "OK" "DynamoDB tables exist"
else
    print_status "ERROR" "DynamoDB tables not found"
    exit 1
fi

# Check if SQS queues exist
echo -e "\n📬 Checking SQS queues..."
if docker exec event-processor-localstack awslocal sqs list-queues | grep -q "event-queue"; then
    print_status "OK" "SQS queues exist"
else
    print_status "ERROR" "SQS queues not found"
    exit 1
fi

# Check recent logs for successful infrastructure setup
echo -e "\n📊 Checking infrastructure setup logs..."
if docker-compose logs event-processor | grep -q "Infrastructure setup completed successfully"; then
    print_status "OK" "Infrastructure setup completed successfully"
else
    print_status "WARN" "Infrastructure setup logs not found (may still be initializing)"
fi

# Check if events are being processed
echo -e "\n📈 Checking event processing..."
if docker-compose logs event-processor | grep -q "Event validated successfully"; then
    print_status "OK" "Events are being processed successfully"
else
    print_status "WARN" "No event processing logs found yet"
fi

echo -e "\n🎉 Basic system verification complete!"
echo -e "\n📝 Next steps:"
echo "1. The system is ready for testing"
echo "2. Events are automatically generated by the producer service"
echo "3. Check logs with: docker-compose logs -f"
echo "4. Monitor health with: curl http://localhost:8080/health"
echo -e "\n🔍 For detailed testing, run: ../scripts/test-system.sh quick"
